package sv.curso.avanzado.persistencia;
// Generated 09-30-2013 10:46:34 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * EstadosUsuario generated by hbm2java
 */
public class EstadosUsuario  implements java.io.Serializable {


     private String codigoEstado;
     private String estadoUsuario;
     private Date fechaCreacion;

    public EstadosUsuario() {
    }

    public EstadosUsuario(String codigoEstado, String estadoUsuario, Date fechaCreacion) {
       this.codigoEstado = codigoEstado;
       this.estadoUsuario = estadoUsuario;
       this.fechaCreacion = fechaCreacion;
    }
   
    public String getCodigoEstado() {
        return this.codigoEstado;
    }
    
    public void setCodigoEstado(String codigoEstado) {
        this.codigoEstado = codigoEstado;
    }
    public String getEstadoUsuario() {
        return this.estadoUsuario;
    }
    
    public void setEstadoUsuario(String estadoUsuario) {
        this.estadoUsuario = estadoUsuario;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }




}


