package sv.curso.avanzado.persistencia;
// Generated 09-30-2013 10:46:34 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Municipios generated by hbm2java
 */
public class Municipios  implements java.io.Serializable {


     private String codigoMunicipio;
     private String municipio;
     private String codigoDepartamento;
     private Date fechaCreacion;

    public Municipios() {
    }

    public Municipios(String codigoMunicipio, String municipio, String codigoDepartamento, Date fechaCreacion) {
       this.codigoMunicipio = codigoMunicipio;
       this.municipio = municipio;
       this.codigoDepartamento = codigoDepartamento;
       this.fechaCreacion = fechaCreacion;
    }
   
    public String getCodigoMunicipio() {
        return this.codigoMunicipio;
    }
    
    public void setCodigoMunicipio(String codigoMunicipio) {
        this.codigoMunicipio = codigoMunicipio;
    }
    public String getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(String municipio) {
        this.municipio = municipio;
    }
    public String getCodigoDepartamento() {
        return this.codigoDepartamento;
    }
    
    public void setCodigoDepartamento(String codigoDepartamento) {
        this.codigoDepartamento = codigoDepartamento;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }




}


