package sv.curso.avanzado.persistencia;
// Generated 09-30-2013 10:46:34 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Paises generated by hbm2java
 */
public class Paises  implements java.io.Serializable {


     private String codigoPais;
     private String pais;
     private Date fechaCreacion;

    public Paises() {
    }

    public Paises(String codigoPais, String pais, Date fechaCreacion) {
       this.codigoPais = codigoPais;
       this.pais = pais;
       this.fechaCreacion = fechaCreacion;
    }
   
    public String getCodigoPais() {
        return this.codigoPais;
    }
    
    public void setCodigoPais(String codigoPais) {
        this.codigoPais = codigoPais;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }




}


