package sv.curso.avanzado.persistencia;
// Generated 09-30-2013 10:46:34 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Roles generated by hbm2java
 */
public class Roles  implements java.io.Serializable {


     private String codigoRol;
     private String nombreRol;
     private Date fechaCreacion;

    public Roles() {
    }

    public Roles(String codigoRol, String nombreRol, Date fechaCreacion) {
       this.codigoRol = codigoRol;
       this.nombreRol = nombreRol;
       this.fechaCreacion = fechaCreacion;
    }
   
    public String getCodigoRol() {
        return this.codigoRol;
    }
    
    public void setCodigoRol(String codigoRol) {
        this.codigoRol = codigoRol;
    }
    public String getNombreRol() {
        return this.nombreRol;
    }
    
    public void setNombreRol(String nombreRol) {
        this.nombreRol = nombreRol;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }




}


