package sv.curso.avanzado.persistencia;
// Generated 09-30-2013 10:46:34 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Sistemas generated by hbm2java
 */
public class Sistemas  implements java.io.Serializable {


     private String codigoSistema;
     private String version;
     private String nombreSistema;
     private String autor;
     private String urlInterna;
     private String urlExterna;
     private String comentarios;
     private Date fechaCreacion;

    public Sistemas() {
    }

	
    public Sistemas(String codigoSistema, String nombreSistema, String autor, String urlInterna, Date fechaCreacion) {
        this.codigoSistema = codigoSistema;
        this.nombreSistema = nombreSistema;
        this.autor = autor;
        this.urlInterna = urlInterna;
        this.fechaCreacion = fechaCreacion;
    }
    public Sistemas(String codigoSistema, String nombreSistema, String autor, String urlInterna, String urlExterna, String comentarios, Date fechaCreacion) {
       this.codigoSistema = codigoSistema;
       this.nombreSistema = nombreSistema;
       this.autor = autor;
       this.urlInterna = urlInterna;
       this.urlExterna = urlExterna;
       this.comentarios = comentarios;
       this.fechaCreacion = fechaCreacion;
    }
   
    public String getCodigoSistema() {
        return this.codigoSistema;
    }
    
    public void setCodigoSistema(String codigoSistema) {
        this.codigoSistema = codigoSistema;
    }
    public String getVersion() {
        return this.version;
    }
    
    public void setVersion(String version) {
        this.version = version;
    }
    public String getNombreSistema() {
        return this.nombreSistema;
    }
    
    public void setNombreSistema(String nombreSistema) {
        this.nombreSistema = nombreSistema;
    }
    public String getAutor() {
        return this.autor;
    }
    
    public void setAutor(String autor) {
        this.autor = autor;
    }
    public String getUrlInterna() {
        return this.urlInterna;
    }
    
    public void setUrlInterna(String urlInterna) {
        this.urlInterna = urlInterna;
    }
    public String getUrlExterna() {
        return this.urlExterna;
    }
    
    public void setUrlExterna(String urlExterna) {
        this.urlExterna = urlExterna;
    }
    public String getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(String comentarios) {
        this.comentarios = comentarios;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }




}


