package sv.curso.avanzado.persistencia;
// Generated 09-30-2013 10:46:34 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * TiposDocumentos generated by hbm2java
 */
public class TiposDocumentos  implements java.io.Serializable {


     private String codigoDocumento;
     private String estadoUsuario;
     private Date fechaCreacion;

    public TiposDocumentos() {
    }

    public TiposDocumentos(String codigoDocumento, String estadoUsuario, Date fechaCreacion) {
       this.codigoDocumento = codigoDocumento;
       this.estadoUsuario = estadoUsuario;
       this.fechaCreacion = fechaCreacion;
    }
   
    public String getCodigoDocumento() {
        return this.codigoDocumento;
    }
    
    public void setCodigoDocumento(String codigoDocumento) {
        this.codigoDocumento = codigoDocumento;
    }
    public String getEstadoUsuario() {
        return this.estadoUsuario;
    }
    
    public void setEstadoUsuario(String estadoUsuario) {
        this.estadoUsuario = estadoUsuario;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }




}


