package sv.curso.avanzado.persistencia;
// Generated 09-30-2013 10:46:34 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private String usuario;
     private String primerApellido;
     private String segundoApellido;
     private String nombres;
     private String tipoDocumento;
     private String nombreDocumento;
     private String noNit;
     private String codigoPais;
     private String codigoDepartamento;
     private String codigoMunicipio;
     private String direccionParticular;
     private String telefonoParticular;
     private String direccionTrabajoUsuario;
     private String telefonoTrabajoUsuario;
     private String faxUsuario;
     private String correoElectronico;
     private String estadoUsuario;
     private Date fechaCreacion;
     private String tipoUsuario;

    public Usuarios() {
    }

	
    public Usuarios(String usuario, String primerApellido, String segundoApellido, String nombres, String tipoDocumento, String nombreDocumento, String noNit, String codigoPais, String codigoDepartamento, String codigoMunicipio, String correoElectronico, String estadoUsuario, Date fechaCreacion) {
        this.usuario = usuario;
        this.primerApellido = primerApellido;
        this.segundoApellido = segundoApellido;
        this.nombres = nombres;
        this.tipoDocumento = tipoDocumento;
        this.nombreDocumento = nombreDocumento;
        this.noNit = noNit;
        this.codigoPais = codigoPais;
        this.codigoDepartamento = codigoDepartamento;
        this.codigoMunicipio = codigoMunicipio;
        this.correoElectronico = correoElectronico;
        this.estadoUsuario = estadoUsuario;
        this.fechaCreacion = fechaCreacion;
        
    }
    public Usuarios(String usuario, String primerApellido, String segundoApellido, String nombres, String tipoDocumento, String nombreDocumento, String noNit, String codigoPais, String codigoDepartamento, String codigoMunicipio, String direccionParticular, String telefonoParticular, String direccionTrabajoUsuario, String telefonoTrabajoUsuario, String faxUsuario, String correoElectronico, String estadoUsuario, Date fechaCreacion, String tipoUsuario) {
       this.usuario = usuario;
       this.primerApellido = primerApellido;
       this.segundoApellido = segundoApellido;
       this.nombres = nombres;
       this.tipoDocumento = tipoDocumento;
       this.nombreDocumento = nombreDocumento;
       this.noNit = noNit;
       this.codigoPais = codigoPais;
       this.codigoDepartamento = codigoDepartamento;
       this.codigoMunicipio = codigoMunicipio;
       this.direccionParticular = direccionParticular;
       this.telefonoParticular = telefonoParticular;
       this.direccionTrabajoUsuario = direccionTrabajoUsuario;
       this.telefonoTrabajoUsuario = telefonoTrabajoUsuario;
       this.faxUsuario = faxUsuario;
       this.correoElectronico = correoElectronico;
       this.estadoUsuario = estadoUsuario;
       this.fechaCreacion = fechaCreacion;
       this.tipoUsuario = tipoUsuario;
    }
   
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPrimerApellido() {
        return this.primerApellido;
    }
    
    public void setPrimerApellido(String primerApellido) {
        this.primerApellido = primerApellido;
    }
    public String getSegundoApellido() {
        return this.segundoApellido;
    }
    
    public void setSegundoApellido(String segundoApellido) {
        this.segundoApellido = segundoApellido;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getTipoDocumento() {
        return this.tipoDocumento;
    }
    
    public void setTipoDocumento(String tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }
    public String getNombreDocumento() {
        return this.nombreDocumento;
    }
    
    public void setNombreDocumento(String nombreDocumento) {
        this.nombreDocumento = nombreDocumento;
    }
    public String getNoNit() {
        return this.noNit;
    }
    
    public void setNoNit(String noNit) {
        this.noNit = noNit;
    }
    public String getCodigoPais() {
        return this.codigoPais;
    }
    
    public void setCodigoPais(String codigoPais) {
        this.codigoPais = codigoPais;
    }
    public String getCodigoDepartamento() {
        return this.codigoDepartamento;
    }
    
    public void setCodigoDepartamento(String codigoDepartamento) {
        this.codigoDepartamento = codigoDepartamento;
    }
    public String getCodigoMunicipio() {
        return this.codigoMunicipio;
    }
    
    public void setCodigoMunicipio(String codigoMunicipio) {
        this.codigoMunicipio = codigoMunicipio;
    }
    public String getDireccionParticular() {
        return this.direccionParticular;
    }
    
    public void setDireccionParticular(String direccionParticular) {
        this.direccionParticular = direccionParticular;
    }
    public String getTelefonoParticular() {
        return this.telefonoParticular;
    }
    
    public void setTelefonoParticular(String telefonoParticular) {
        this.telefonoParticular = telefonoParticular;
    }
    public String getDireccionTrabajoUsuario() {
        return this.direccionTrabajoUsuario;
    }
    
    public void setDireccionTrabajoUsuario(String direccionTrabajoUsuario) {
        this.direccionTrabajoUsuario = direccionTrabajoUsuario;
    }
    public String getTelefonoTrabajoUsuario() {
        return this.telefonoTrabajoUsuario;
    }
    
    public void setTelefonoTrabajoUsuario(String telefonoTrabajoUsuario) {
        this.telefonoTrabajoUsuario = telefonoTrabajoUsuario;
    }
    public String getFaxUsuario() {
        return this.faxUsuario;
    }
    
    public void setFaxUsuario(String faxUsuario) {
        this.faxUsuario = faxUsuario;
    }
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }
    public String getEstadoUsuario() {
        return this.estadoUsuario;
    }
    
    public void setEstadoUsuario(String estadoUsuario) {
        this.estadoUsuario = estadoUsuario;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    
    public String getTipoUsuario(){
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(String tipoUsuario){
        this.tipoUsuario = tipoUsuario;
    }




}


