package sv.curso.avanzado.persistencia;
// Generated 09-30-2013 10:46:34 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * UsuariosRolId generated by hbm2java
 */
public class UsuariosRolId  implements java.io.Serializable {


     private String usuario;
     private String codigoRol;
     private String codigoOpcion;
     private Date fechaCreacion;

    public UsuariosRolId() {
    }

    public UsuariosRolId(String usuario, String codigoRol, String codigoOpcion, Date fechaCreacion) {
       this.usuario = usuario;
       this.codigoRol = codigoRol;
       this.codigoOpcion = codigoOpcion;
       this.fechaCreacion = fechaCreacion;
    }
   
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getCodigoRol() {
        return this.codigoRol;
    }
    
    public void setCodigoRol(String codigoRol) {
        this.codigoRol = codigoRol;
    }
    public String getCodigoOpcion() {
        return this.codigoOpcion;
    }
    
    public void setCodigoOpcion(String codigoOpcion) {
        this.codigoOpcion = codigoOpcion;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsuariosRolId) ) return false;
		 UsuariosRolId castOther = ( UsuariosRolId ) other; 
         
		 return ( (this.getUsuario()==castOther.getUsuario()) || ( this.getUsuario()!=null && castOther.getUsuario()!=null && this.getUsuario().equals(castOther.getUsuario()) ) )
 && ( (this.getCodigoRol()==castOther.getCodigoRol()) || ( this.getCodigoRol()!=null && castOther.getCodigoRol()!=null && this.getCodigoRol().equals(castOther.getCodigoRol()) ) )
 && ( (this.getCodigoOpcion()==castOther.getCodigoOpcion()) || ( this.getCodigoOpcion()!=null && castOther.getCodigoOpcion()!=null && this.getCodigoOpcion().equals(castOther.getCodigoOpcion()) ) )
 && ( (this.getFechaCreacion()==castOther.getFechaCreacion()) || ( this.getFechaCreacion()!=null && castOther.getFechaCreacion()!=null && this.getFechaCreacion().equals(castOther.getFechaCreacion()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUsuario() == null ? 0 : this.getUsuario().hashCode() );
         result = 37 * result + ( getCodigoRol() == null ? 0 : this.getCodigoRol().hashCode() );
         result = 37 * result + ( getCodigoOpcion() == null ? 0 : this.getCodigoOpcion().hashCode() );
         result = 37 * result + ( getFechaCreacion() == null ? 0 : this.getFechaCreacion().hashCode() );
         return result;
   }   


}


