package sv.curso.avanzado.persistencia;
// Generated 09-30-2013 10:46:34 PM by Hibernate Tools 3.2.1.GA



/**
 * UsuariosRol generated by hbm2java
 */
public class UsuariosRol  implements java.io.Serializable {


     private UsuariosRolId id;

    public UsuariosRol() {
    }

    public UsuariosRol(UsuariosRolId id) {
       this.id = id;
    }
   
    public UsuariosRolId getId() {
        return this.id;
    }
    
    public void setId(UsuariosRolId id) {
        this.id = id;
    }




}


